# Generated by Django 5.1.4 on 2024-12-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_carrinho_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
