# Generated by Django 5.1.5 on 2025-01-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_pedido_pedido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='estrelas',
            field=models.IntegerField(choices=[(1, '1 estrela'), (2, '2 estrela'), (3, '3 estrela'), (4, '4 estrela'), (5, '5 estrela')], default=5),
        ),
    ]
